### ISSUE TITLE
service firewalld disable failed when firewall is not installed

### ISSUE THREAD

**Issue by tbludau** [rhmk/ansible-hana-examples#18]
check if package firewalld is installed
hana-host/tasks/RedHat7/service-configuration.yml:- name: disable firewalld
hana-host/tasks/RedHat7/service-configuration.yml:  service: name=firewalld state=stopped enabled=no
preconfigure/tasks/RedHat7/service-configuration.yml:- name: disable firewalld
preconfigure/tasks/RedHat7/service-configuration.yml:  service: name=firewalld state=stopped enabled=no

**Comment by rhmk** [comment]
moved to galaxy preconfigure role, hence closed here
