### ISSUE TITLE
replace unrar with unar from epel

### ISSUE THREAD

**Issue by Klaas-** [rhmk/ansible-hana-examples#23]
https://admin.fedoraproject.org/pkgdb/package/rpms/unar/ 

Greetings
Klaas

**Comment by rhmk** [comment]
Thanks Klaas, 
I will check that during the next rework

**Comment by rhmk** [comment]
Works perfectly well.

**Comment by Klaas-** [comment]
maybe you could try to get unar into base or sap repositories :)

**Comment by rhmk** [comment]
moved to galaxy preconfigure role, hence closed here
