### ISSUE TITLE
Restructure documentation 

### ISSUE THREAD

**Issue by kyleabenson** [rhmk/ansible-hana-examples#25]
Currently it looks like there are two locations for usage -- the general README.md and under docs/hana-host.txt

Generally when publishing playbooks with nested roles, it's good to provide a high level document as README.md and then provide a README for each respective role that explains it's purpose. 

We also don't point users from the current README to docs/hana-host.txt, so at the very least if not changing the structure the items under docs/ should be updated.

**Comment by rhmk** [comment]
Thanks for your feedback. I am not very experienced on best practise how to structure that. Is there any general style guide, how to use nested roles and more interesting how to share configuration variables between playbooks that are named differently.
In general I think the playbooks should be structured like linux-system-roles

**Comment by kyleabenson** [comment]
Hey @rhmk! I would be happy to assist on the creation/rework of this. I will email you with additional details.

**Comment by rhmk** [comment]
Documentation has been simplified, by moving it to the galaxy roles at: https://github.com/mk-ansible-roles where it belongs. This repository will be changed to install the required galaxy roles and documenting use cases instead of holding the complete roles

**Comment by rhmk** [comment]
roles are now documented at galaxy. Close the documentation here
