### ISSUE TITLE
preconfigure sap-mount-media

### ISSUE THREAD

**Issue by mschlarb** [rhmk/ansible-hana-examples#26]
task: sap-mount-media.yml

- file:
    name: "{{ installroot }}"
    state: directory
    owner: root
    group: root

This tasks fails because the installroot is already NFS mounted

**Comment by tbludau** [comment]
@rhmk is this something we can delete while reorg base-host-setup #13 ?

**Comment by rhmk** [comment]
This is part of the media check in saphana-preconfigure. So it cannot be deleted but the checks should be improved ...

**Comment by rhmk** [comment]
moved to galaxy preconfigure role, hence closed here
