### ISSUE TITLE
Cleanup of system registration in base_host_setup

### ISSUE THREAD

**Issue by kyleabenson** [rhmk/ansible-hana-examples#29]
Base Host setup

There is a lot of commented lines in this role. Comements should be moved from main.yml into the role README.md

**Task: Enable Debugging**
Why do we set debug to 3 on one, empty task? I do not see debug msg's anywhere else in base-host-setup

**Include statements**
Both optional
We call both system-registration-part1.yml & RH7 | RH6 based on conditional check_repos and system release
What about the RHEL 7.2 task being commented out?
Can we enforce a desired state here?
Can we set repos based on release?
What about task 'reset all repositories'? Shouldn't this be all that the system is configured for?

Lots of conditional logic. Things like 'when check_repos'.. doesn't need to be setup.
We should confirm repositories are configured and if not, pass an option to run a config for RHSM

**Comment by kyleabenson** [comment]
@tbludau a more direct question too -- why are these two variables set differently in other places?
```
force_rhel_release: 7.3
force_repo_reset: false
```

If someone is deploying SAP HANA, wouldn't it be a safe assumption for them to use that host for only that purpose? If so, shouldn't we disable other repos?

**Comment by tbludau** [comment]
I think this could be closed in based of the reorg of base-host-setup. #13 because its not necessary anymore

**Comment by rhmk** [comment]
Closing the issue, as it has been resolved
